# Generated by Django 2.0.6 on 2018-06-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_lessons_lesson_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
