# Generated by Django 2.0.6 on 2018-06-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_trial',
            field=models.BooleanField(default=True),
        ),
    ]
