# Generated by Django 2.0.6 on 2018-06-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_free_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paying_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
